### ISSUE TITLE
Get Window Identifiers returns nothing

### ISSUE THREAD

**Issue by ghost** [MarkusBernhardt/robotframework-selenium2library-java#38]
Hi,

I am using 'Get Window Identifiers' keyword with jybot and nothing is being returned. However when I run the same test case with pybot the browser identifies are being returned. 

Jybot: log output

KEYWORD: @{windows} = Selenium2Library.Get Window Identifiers
Documentation:  
Returns the id attributes of all windows known to the current browser
Start / End / Elapsed:  20131121 11:29:02.326 / 20131121 11:29:03.064 / 00:00:00.738
11:29:02.327    TRACE   Arguments: [  ]
11:29:03.065    TRACE   Return: [null, null]
11:29:03.066    INFO    @{windows} = [ None | None ]

pybot: log output

KEYWORD: @{windows} = Selenium2Library.Get Window Identifiers
Documentation:  
Returns and logs id attributes of all windows known to the browser.
Start / End / Elapsed:  20131121 11:10:51.407 / 20131121 11:11:07.372 / 00:00:15.965
11:11:07.372    INFO    Altogether 2 items.
                                        1: undefined
                                        2: undefined
11:11:07.372    INFO    @{windows} = [ undefined | undefined ]

For jybot I am using the robotframework-selenium2library-java-1.4.0.0-jar-with-dependencies.jar. 

Is this a bug? any help would be much appreciated. 

Thanks

ht

**Comment by pvsharma** [comment]
I am getting the same error , Can anyone please help in fixing this problem.


We recently moved to Java 1.8 and this is when we started getting the same error message.
