### ISSUE TITLE
Feature Request: support Ext.ComponentQuery

### ISSUE THREAD

**Issue by BenjaminZaiser** [MarkusBernhardt/robotframework-selenium2library-java#4]
Hi,

I would like to use Ext.ComponentQuery to easily write locators for ExtJS applications:

_Example:_

``` javascript
Input Text    extJs=(Ext.ComponentQuery.query("textfield[name='first_name']")[0]).getInputId()    Max
Click Element    extJs=(Ext.ComponentQuery.query("button[text='Save']")[0]).getId()
```

I think, the "Add Location Strategy" is not applicable, because the arguments are not evaluated. 

Please could you add a StrategyEnum to support the ExtJS ComponentQuery, just like you already support e.g. JQuery Sizzle?

Thanks.

**Comment by liputao** [comment]
`No keyword with name 'return window.document.getElementById((Ext.ComponentQuery.query(arguments[0])[0]).btnEl.id);' found`

Always this error?????Anything wrong?
