### ISSUE TITLE
Appium support?

### ISSUE THREAD

**Issue by BenjaminZaiser** [MarkusBernhardt/robotframework-selenium2library-java#61]
Hi Markus,

in the current master you've added support for Appium. Did you add the library to support testing webpages on smartphones or do you want to extend your library to support native Android / iOS app testing by using Appium?

I'm just asking, because I need a Robotframework library for Appium to do native app testing. Currently there is only a robotframework wrapper library existing for the python client (https://github.com/jollychang/robotframework-appiumlibrary); but because I like Java more and I think  the appium java client is more sophisticated (and because of the other pros you already mentioned in the readme of your library), a new wrapper library for the appium java client has to be implemented (because there is currently none available).

Before I start writing such a wrapper library from scratch: do you think your robotframework-selenium2library-java be extended to support the Appium specific keywords, like swipe, tap, hideKeyboard, install app, close app, etc? Can you think of a concept on how to integrate those keywords to your library? Maybe I can then support you in implementing those keywords.

Thanks
Ben

**Comment by MarkusBernhardt** [comment]
Hi Ben,

to be honest I never used appium. I only added it on request by some users. How to use it I have no idea. 

I will push out a new version 1.4.0.8 today containing the newest appium libraries. Perhaps you want to checkout that.

Cheers,
Markus
