### ISSUE TITLE
Unable to pass in Firefox profile directory when opening browser

### ISSUE THREAD

**Issue by ali-feint** [MarkusBernhardt/robotframework-selenium2library-java#63]
Unable to pass in Firefox profile directory when opening browser.

The Open Browser documentation states that you can pass in the ff_profile_dir parameter to set the firefox profile directory.  It looks like this isnt parsed out in this library.

_Optional 'ff_profile_dir' is the path to the firefox profile dir if you wish to overwrite the default._
http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html#Open%20Browser

I really need to use this, so it would be good if someone could fix.

Thanks

**Comment by MarkusBernhardt** [comment]
Hi,
this works differently in the java version of the library. Please look into the documentation of the java version: 
https://repo1.maven.org/maven2/com/github/markusbernhardt/robotframework-selenium2library-java/1.4.0.6/robotframework-selenium2library-java-1.4.0.6-libdoc.html#Open%20Browser

I believe this solution is better for two reasons:
- A firefox profile is dependent on the version of firefox. So, when you update your browser, you have to update the profile directory and can't easily go back later. The java version always creates a standard profile that matches your browser version and then adds your parameters and plugins.
- It also work with Safari and Chrome.

Cheers,
Markus

**Comment by ali-feint** [comment]
Thank you, I think I can figure that out.

One question: is it possible to boot up from a specific executable?  I want to provide a pre packaged binary, and always run that.

thanks
