### ISSUE TITLE
Update Selenium version to 2.45

### ISSUE THREAD

**Issue by mobichel** [MarkusBernhardt/robotframework-selenium2library-java#64]
Selenium 2.45 has been released with important fixes for FF36, could you please upgrade selenium version.

https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

Thanks!

**Comment by markfink** [comment]
as a workaround you can build it yourself. I did that using selenium 2.46.

In the pom.xml I changed to version to **2.46.0** for the following groups:
* org.seleniumhq.selenium
* org.seleniumhq.selenium

To make it work I had to add another dependency:
```xml
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-exec</artifactId>
	<version>1.3</version>
</dependency>
```

To initiate the build:
$ mvn package

**Comment by asitishere** [comment]
Thanks Mark.

Please suggest how can I run my test .robot file or complete test suite using the .jar file with all dependencies after  mvn package.

java -jar depPackage.jar
no main manifest attribute

I want to run test cases with the dependency package created.

Please help.

**Comment by markfink** [comment]
this is a little off-topic in relation to the OP but why not...
In an enterprise setup (which I assume is your case) you would put the package into your local nexus. Just ask your tech lead how to do that. Alternatively add it as an external jar. The following thread discusses the options:
http://stackoverflow.com/questions/5692256/maven-best-way-of-linking-custom-external-jar-to-my-project

Personally I do not use maven to run my robotframework tests. I just add the jar to my classpath.
As I said this is a workaround. Of course the clean solution would be that the package maintainer provides an update.

**Comment by asitishere** [comment]
Thanks a lot Mark.

I managed to get it done now I build the dependency package and run with selenium jar ( From Command mode) for Test Suite or Specific Test cases . In other case I use maven run.

Regards
Asit

**Comment by mobichel** [comment]
Thank you Mark!

I will build it myself.

**Comment by asitishere** [comment]
Hello mobichel,

I managed to build with Latest version of selenium . Please let me know . I can pass the steps.

Regards
Asit

**Comment by mobichel** [comment]
Hello Asit,

I have successfully built with Selenium version 2.45, just have to skip some unit tests.

Thanks!

**Comment by MarkusBernhardt** [comment]
Pushing out an updated version today
