### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by asitishere** [MarkusBernhardt/robotframework-selenium2library-java#68]
Created the dependance file using mvn package and then tried executing the test cases from command line.

Failed with  "Could not find or load main class"

C:\digital-testing\robotframework-Redesign\target>java -cp robotframework-2.8.7.
jar robotDep.jar org.robotframework.RobotFramework myTest.txt
Error: Could not find or load main class robotDep.jar

**Comment by asitishere** [comment]
I tried the same way Mark suggested in one of the post 

 MarkusBernhardt commented on 11 Dec 2013
Hi, also the fat jar does not contain the robotframework itself. You need to get also that jar and put both into the classpath. Don't use the "-jar" option. Use the "-cp" option. Something like: java -cp robotframework-2.8.1.jar;robotframework-selenium2library-java-1.4.0.0-jar-with-dependencies.jar org.robotframework.RobotFramework myTest.txt Cheers, Markus

**Comment by asitishere** [comment]
Please suggest once i compile my java files and on any change in Test cases on command mvn integartion-test it re compile and then run.

Is there any way to ONLY run the testing using the old .class file considering no change in code.

Please please suggest .

**Comment by HelioGuilherme66** [comment]
I think you missed a ; in the classpath for robotDep.jar.
Try this:
java -cp robotframework-2.8.7.jar;robotDep.jar
org.robotframework.RobotFramework myTest.txt

**Comment by asitishere** [comment]
Thanks a Ton Guilherme
It worked for me.

Shall I ask few other queries if you fine related to robot framework Java port develop by Mark.
