### ISSUE TITLE
Library not loading with Robot Framework 2.9

### ISSUE THREAD

**Issue by Hi-Fi** [MarkusBernhardt/robotframework-selenium2library-java#73]
Tried to change existing tests to use RF 2.9, and got following error:
```
[ ERROR ] Error in file 'C:\work\testautomation\tests\s2test.txt': Initializing test library 'Selenium2Library' with no arguments failed: maximum recursion depth exceeded (Java StackOverflowError)
Traceback (most recent call last):
  None
```

I run tests with Gradle, so just changed version of the dependancy in build.gradle.

There're some changes in Python version of library because of RF2.9. Hopefully there's plan to support RF2.9 with this java-version, too.

Tested with simplified case:
```
*** Settings ***
Library           Selenium2Library

*** Test Cases ***
TEST
    Open Browser    www.google.com    ${BROWSER}
    Capture Page Screenshot
    Close Browser
```

**Comment by ali-feint** [comment]
@Hi-Fi how do you run the tests with Gradle?

**Comment by Hi-Fi** [comment]
Gradle runner: https://gist.github.com/Hi-Fi/f18f40b59d1743e5b284

**Comment by Hi-Fi** [comment]
Tests are currently passing in my version, but libdoc isn't working for some reason. Maven just gives cryptic 
```
Initializing test library 'Selenium2Library' with no arguments failed: maximum recursion depth exceeded (Java StackOverflowError)
Traceback (most recent call last):
  None
```
error, and while trying to run that with RF jar directly, there' some other errors.

**Comment by aquator** [comment]
Any chance getting the fix merged and released soon?

**Comment by MarkusBernhardt** [comment]
Will try to look into that in the evening

**Comment by diakula** [comment]
Getting similar error: 
```
 Initializing test library 'Selenium2Library' with no arguments failed: maximum recursion depth exceeded (Java StackOverflowError)
```
Using robotframework 2.9.1.

**Comment by jordanwalsh23** [comment]
Same error on robotframework 2.9.2. 

Was there any documented solution to this?

`Initializing test library 'Selenium2Library' with no arguments failed: maximum recursion depth exceeded (Java StackOverflowError)`

**Comment by Hi-Fi** [comment]
Yes, error is with all versions of Robot Framework 2.9.x because of breaking changes. Update/fix made already at #74. 

Same fixes were also introduced to Python version of Selenium2Library.

**Comment by Marco85Li** [comment]
Is the fixed/updated release available on maven repositories?

**Comment by MarkusBernhardt** [comment]
Merged in. Will be released today. THANKS for the fix.
