### ISSUE TITLE
Selenium update (v 2.48.2)

### ISSUE THREAD

**Issue by pedromauricio** [MarkusBernhardt/robotframework-selenium2library-java#77]
Hi there, just wanted to drop you a line about Selenium, the one in use doesn't work with the latest version of FF. Is there any chance of getting Selenium updated to the latest (2.48.2)?

Cheers

**Comment by MarkusBernhardt** [comment]
Will try to release today

**Comment by pedromauricio** [comment]
Great, thanks a lot for this!
